FROM alpine:3.21@sha256:48b0309ca019d89d40f670aa1bc06e426dc0931948452e8491e3d65087abc07d AS xsh-unpack

ARG XSH_RELEASE=release-d09c6c3305ab8c650043bd8d32e03f2db6509e97
ARG XSH_RELEASE_ARCH=aarch64
ARG XSH_RELEASE_XSH_SHA256=bc9117b8ac70c726002835e7ab1eaff0d45ede7b067bc85ddba7971eb8b8ffbb
ARG XSH_RELEASE_XSHI_SHA256=5cf2f028fd0f0e6cbae213d7037e28e1aa92ca74768c5fce5e300d9725014bb6
ARG XSH_RELEASE_XSHT_SHA256=86c2d1ac329702c0def779adb47640f84cdda9466630e2c98681750fc037a2e2

ADD --checksum=sha256:${XSH_RELEASE_XSH_SHA256} https://github.com/laputa-systems/xsh/releases/download/${XSH_RELEASE}/xsh-${XSH_RELEASE}-${XSH_RELEASE_ARCH}-linux-musl /tmp/xsh
ADD --checksum=sha256:${XSH_RELEASE_XSHI_SHA256} https://github.com/laputa-systems/xsh/releases/download/${XSH_RELEASE}/xshi-${XSH_RELEASE}-${XSH_RELEASE_ARCH}-linux-musl /tmp/xshi
ADD --checksum=sha256:${XSH_RELEASE_XSHT_SHA256} https://github.com/laputa-systems/xsh/releases/download/${XSH_RELEASE}/xsht-${XSH_RELEASE}-${XSH_RELEASE_ARCH}-linux-musl /tmp/xsht

RUN mkdir -p /image/usr/bin /image/bin /image/tmp /image/var/tmp && \
    cp /tmp/xsh /image/bin/xsh && \
    cp /tmp/xshi /image/bin/xshi && \
    cp /tmp/xsht /image/bin/xsht && \
    chmod 0755 /image/bin/xsh /image/bin/xshi /image/bin/xsht && \
    printf '#!/bin/xsh\nrun /bin/xshi @args ?\n' > /image/usr/bin/sh && \
    cp /image/usr/bin/sh /image/bin/sh && \
    chmod 0755 /image/usr/bin/sh /image/bin/sh && \
    chmod 1777 /image/tmp /image/var/tmp

FROM scratch

COPY --from=xsh-unpack /image/ /

ENV PATH=/bin:/usr/bin \
    XSH_MODULE_PATH=/src/packages

WORKDIR /src/packages

CMD ["xsht", "test", "--cov", "--cov-json", "target/coverage/pm.json", "tests/xsh/pm_recipe.xsh", "tests/xsh/pm_graph.xsh", "tests/xsh/pm_plan.xsh", "tests/xsh/pm_store.xsh", "tests/xsh/pm_root.xsh", "tests/xsh/pm_execute.xsh", "tests/xsh/pm_publish.xsh", "tests/xsh/pm_generation.xsh", "tests/xsh/pm_cli.xsh"]
