FROM alpine:3.21@sha256:48b0309ca019d89d40f670aa1bc06e426dc0931948452e8491e3d65087abc07d AS xsh-unpack

ARG XSH_RELEASE=release-e12de8c8ce6388bcbf80df96bf57ebd8afc2d0df
ARG XSH_RELEASE_ARCH=aarch64
ARG XSH_RELEASE_SHA256=0874226398877b375ce2a8453f7b587d75ec6a40a601fddcf33fd80dbdf08a27

ADD --checksum=sha256:${XSH_RELEASE_SHA256} https://github.com/laputa-systems/xsh/releases/download/${XSH_RELEASE}/xsh-multicall-${XSH_RELEASE}-${XSH_RELEASE_ARCH}-linux-musl /tmp/xsh-multicall

RUN mkdir -p /image/usr/bin /image/bin /image/tmp /image/var/tmp && \
    cp /tmp/xsh-multicall /image/bin/xsh-multicall && \
    chmod 0755 /image/bin/xsh-multicall && \
    for command_name in xsh xshi xsht; do ln -s xsh-multicall /image/bin/"${command_name}"; done && \
    printf '#!/bin/xsh\nrun /bin/xshi @args ?\n' > /image/usr/bin/sh && \
    cp /image/usr/bin/sh /image/bin/sh && \
    chmod 0755 /image/usr/bin/sh /image/bin/sh && \
    chmod 1777 /image/tmp /image/var/tmp

FROM scratch

COPY --from=xsh-unpack /image/ /

ENV PATH=/bin:/usr/bin

WORKDIR /src/packages

CMD ["xsht", "test", "tests/xsh/pm.xsh"]
