use pm.env as pm_env

export let name = "libdrm"

export let ver = "2.4.127"

export let rel = "8"

export let deps = ["musl", "libudev-zero"]

export let mkdeps = ["llvm-toolchain", "linux", "muon", "samurai", "pkgconf", "libudev-zero"]

export let sources = [p"https://dri.freedesktop.org/libdrm/libdrm-VERSION.tar.xz"]

export let checksums = [
  "051aeb3e542a57621018ffc443fb088dd69b78eef0ce4808b604ce0feac9f47f",
]

type Modifier = {vendor: Str, mod: Str, name: Str}

export let filetree = [
  {path: p"usr/include/libdrm/amdgpu_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/drm.h", kind: "file"},
  {path: p"usr/include/libdrm/drm_fourcc.h", kind: "file"},
  {path: p"usr/include/libdrm/drm_mode.h", kind: "file"},
  {path: p"usr/include/libdrm/drm_sarea.h", kind: "file"},
  {path: p"usr/include/libdrm/i915_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/mach64_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/mga_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/msm_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/nouveau_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/qxl_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/r128_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/radeon_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/savage_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/sis_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/tegra_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/vc4_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/via_drm.h", kind: "file"},
  {path: p"usr/include/libdrm/virtgpu_drm.h", kind: "file"},
  {path: p"usr/include/libsync.h", kind: "file"},
  {path: p"usr/include/xf86drm.h", kind: "file"},
  {path: p"usr/include/xf86drmMode.h", kind: "file"},
  {path: p"usr/lib/libdrm.so", kind: "symlink"},
  {path: p"usr/lib/libdrm.so.2", kind: "symlink"},
  {path: p"usr/lib/libdrm.so.2.127.0", kind: "binary"},
  {path: p"usr/lib/pkgconfig/libdrm.pc", kind: "file"},
]

proc write_format_modifier_table() [fs, error] {
  let header = p"include/drm/drm_fourcc.h"
  var intel = []
  var modifiers: List[Modifier] = []
  var vendors = []

  for line in header.read_text()?.split("\n") {
    let words = line.words()

    if words.len() >= 2 {
      let modifier_name = words[1]

      if modifier_name.starts_with("I915_FORMAT_MOD_") {
        intel = intel.push(modifier_name.replace("I915_FORMAT_MOD_", ""))
      } else if modifier_name.starts_with("DRM_FORMAT_MOD_VENDOR_") {
        vendors = vendors.push(modifier_name.replace("DRM_FORMAT_MOD_VENDOR_", ""))
      } else if modifier_name.starts_with("DRM_FORMAT_MOD_") and ! ("(" in modifier_name) and ! ("*" in modifier_name) and ! ("-" in modifier_name) {
        let entry = modifier_name.replace("DRM_FORMAT_MOD_", "")
        let parts = entry.split("_")

        if parts.len() >= 2 {
          let vendor = parts[0]
          let mod = entry.replace(f"${vendor}_", "")

          if ! (vendor == "ARM" and (mod == "TYPE_AFBC" or mod == "TYPE_MISC" or mod == "TYPE_AFRC")) {
            modifiers = modifiers.push({vendor, mod, name: mod})
          }
        }
      }
    }
  }

  var body = [
    "/* AUTOMATICALLY GENERATED by the Laputa libdrm package. */",
    "static const struct drmFormatModifierInfo drm_format_modifier_table[] = {",
    "    { DRM_MODIFIER_INVALID(NONE, INVALID) },",
    "    { DRM_MODIFIER_LINEAR(NONE, LINEAR) },",
  ]

  for mod in intel {
    body = body.push(f"    { DRM_MODIFIER_INTEL(${mod}, ${mod}) },")
  }

  for mod in modifiers {
    body = body.push(f"    { DRM_MODIFIER(${mod.vendor}, ${mod.mod}, ${mod.name}) },")
  }

  body = body.push("};")
  body = body.push("static const struct drmFormatModifierVendorInfo drm_format_modifier_vendor_table[] = {")

  for vendor in vendors {
    body = body.push(f"    { DRM_FORMAT_MOD_VENDOR_${vendor}, \"${vendor}\" },")
  }

  body = body.push("};")
  fs.write(p"generated_static_table_fourcc.h", body.join("\n"))?
}

proc patch_python_generator() [fs, error] {
  write_format_modifier_table()?
  let meson = p"meson.build"
  var text = meson.read_text()?

  text = text.replace(
    """python3 = import('python').find_installation()
format_mod_static_table = custom_target(
  'format_mod_static_table',
  output : 'generated_static_table_fourcc.h',
  input : 'include/drm/drm_fourcc.h',
  command : [python3, files('gen_table_fourcc.py'), '@INPUT@', '@OUTPUT@'])
""",
    """format_mod_static_table = files('generated_static_table_fourcc.h')
""",
  )

  fs.write(meson, text)?
}

export proc build(dest: Path) [fs, process, env, error] {
  let muon = process.which("muon")?
  let jobs_flag = f"-j${cpu.count()}"
  let pc = pm_env.pkg_config_context()?
  patch_python_generator()?

  env {
    LD_LIBRARY_PATH = pc.ld_library_path
    PKG_CONFIG = pc.pkg_config
    PKG_CONFIG_LIBDIR = pc.pkg_config_libdir
    PKG_CONFIG_PATH = pc.pkg_config_path
    PKG_CONFIG_SYSROOT_DIR = pc.pkg_config_sysroot
  } {
    run $muon "setup" pm_env.meson_prefix_arg() pm_env.meson_libdir_arg() "-Ddefault_library=shared" "-Dudev=true" "-Dtests=false" "-Dinstall-test-programs=false" "-Dman-pages=disabled" "-Dvalgrind=disabled" "-Dcairo-tests=disabled" "-Dintel=disabled" "-Dradeon=disabled" "-Damdgpu=disabled" "-Dnouveau=disabled" "-Dvmwgfx=disabled" "-Domap=disabled" "-Dexynos=disabled" "-Dfreedreno=disabled" "-Dtegra=disabled" "-Dvc4=disabled" "-Detnaviv=disabled" "build" ?
    run $muon "-C" "build" samu $jobs_flag ?

    env {
      DESTDIR = dest
    } {
      run $muon "-C" "build" install ?
    } ?
  } ?
}
