export let name = "xkeyboard-config"

export let ver = "2.45"

export let rel = "9"

export let deps = []

export let mkdeps_host = []

export let upstream_sources = [
  {
    source: p"https://xorg.freedesktop.org/archive/individual/data/xkeyboard-config/xkeyboard-config-VERSION.tar.xz",
    kind: "auto",
    architectures: ["all"],
    checksums: [{arch: "all", sha256: "169e075a92d957a57787c199e84e359df2931b7196c1c5b4a3d576ee6235a87c"}],
  },
]

export let filetree = [
  {path: p"usr", kind: "tree"},
  {path: p"usr/share/X11/xkb", kind: "symlink"},
  {path: p"usr/share/pkgconfig/xkeyboard-config.pc", kind: "symlink"},
  {path: p"usr/share/xkeyboard-config-2/symbols/caps", kind: "symlink"},
  {path: p"usr/share/xkeyboard-config-2/symbols/esperanto", kind: "symlink"},
  {path: p"usr/share/xkeyboard-config-2/symbols/grp", kind: "symlink"},
  {path: p"usr/share/xkeyboard-config-2/symbols/japan", kind: "symlink"},
  {path: p"usr/share/xkeyboard-config-2/symbols/korean", kind: "symlink"},
  {path: p"usr/share/xkeyboard-config-2/symbols/lv2", kind: "symlink"},
  {path: p"usr/share/xkeyboard-config-2/symbols/lv3", kind: "symlink"},
  {path: p"usr/share/xkeyboard-config-2/symbols/lv5", kind: "symlink"},
]

proc rule_parts(ruleset: Str) [fs, error] -> Result[List[Path]] {
  let entries = fs.ls(p"rules")?
    |> where .kind == "file"
    |> where .name.ends_with(".part")
    |> sort-by .name

  var parts = []

  for entry in entries {
    if ! ("base." in entry.name) and ! ("evdev." in entry.name) {
      parts = parts.push(entry.path)
    } else if f"${ruleset}." in entry.name {
      parts = parts.push(entry.path)
    }
  }

  parts
}

proc merged_rules(ruleset: Str) [fs, error] -> Result[Str] {
  var output = f"""// DO NOT EDIT THIS FILE - IT WAS AUTOGENERATED BY xsh FROM rules/*.part
//
"""

  var seen_headers: Map[Bool] = {}

  for part in rule_parts(ruleset)? {
    let lines = part.read_text()?.split("\n")
    var start = 0

    if lines.len() > 0 and lines[0].starts_with("! ") {
      let header = lines[0].split("//")[0].trim()

      if ! seen_headers.get(header, false) {
        output = f"""${output}
${lines[0]}
"""

        seen_headers[header] = true
      }

      start = 1
    }

    var index = start

    while index < lines.len() {
      output = f"""${output}${lines[index]}
"""

      index += 1
    }
  }

  output
}

export proc build(dest: Path) [fs, error] {
  let base = fp"${dest}/usr/share/xkeyboard-config-2"
  fs.mkdir(base)?

  for dir in [p"compat", p"geometry", p"keycodes", p"symbols", p"types"] {
    fs.copy_tree(dir, fp"${base}/${dir.name}", parents: true, overwrite: true)?
  }

  fs.mkdir(fp"${base}/rules")?

  for ruleset in ["base", "evdev"] {
    fs.write(fp"${base}/rules/${ruleset}", merged_rules(ruleset)?)?
    let xml = fp"rules/${ruleset}.xml"
    let xml_source = if fs.exists(xml)? { xml } else { p"rules/base.xml" }
    fs.install(xml_source, fp"${base}/rules/${ruleset}.xml", 0o644, parents: true, overwrite: true)?
    let extras = fp"rules/${ruleset}.extras.xml"
    let extras_source = if fs.exists(extras)? { extras } else { p"rules/base.extras.xml" }
    fs.install(extras_source, fp"${base}/rules/${ruleset}.extras.xml", 0o644, parents: true, overwrite: true)?
    fs.write(fp"${base}/rules/${ruleset}.lst", "")?
  }

  fs.install(p"rules/xkb.dtd", fp"${base}/rules/xkb.dtd", 0o644, parents: true, overwrite: true)?
  fs.mkdir(fp"${dest}/usr/share/X11")?
  fs.symlink(../xkeyboard-config-2, fp"${dest}/usr/share/X11/xkb")?
  fs.mkdir(fp"${dest}/usr/share/pkgconfig")?

  fs.write(
    fp"${dest}/usr/share/pkgconfig/xkeyboard-config-2.pc",
    """prefix=/usr
datadir=\${prefix}/share
xkb_root=\${datadir}/xkeyboard-config-2
xkb_base=\${datadir}/X11/xkb

Name: XKeyboardConfig
Description: X Keyboard configuration data
Version: 2.45
""",
  )?

  fs.symlink(p"xkeyboard-config-2.pc", fp"${dest}/usr/share/pkgconfig/xkeyboard-config.pc")?
}
