use kbuild

proc render_fragments(fragments: List[Path]) [fs, error] -> Result[Str] {
  var out = """# Generated by linux_config.xsh from package config fragments.
#
"""

  for fragment in fragments {
    if ! fragment.exists()? {
      return Err(
        ScriptError.Failed("linux-config-fragment-missing", f"missing kernel config fragment ${fragment.display()}"),
      )
    }

    out = f"""${out}${fragment.read_text()?.trim()}
"""
  }

  return out
}

export proc write_resolved_config(root: Path, srcarch: Str, fragments: List[Path], out: Path) [fs, error] {
  let _ = {root: root.display(), srcarch}
  kbuild.write_text_if_changed(out, render_fragments(fragments)?)?
}
