##! XSH module `linux_config` package and build operations.
use kbuild

proc resolved_fragment_input(input: Path) [fs, env, error] -> Result[Path] {
  let source_root = (env.get("XSH_PM_SOURCE_DIR") ?? "").trim()

  if source_root != "" {
    let staged = fp"${source_root}/.laputa-inputs/${input.display()}"

    if staged.exists()? {
      return staged
    }
  }

  let recipe_root = (env.get("XSH_PM_RECIPE_DIR") ?? "").trim()

  if recipe_root != "" {
    let copied = fp"${recipe_root}/${input.display()}"

    if copied.exists()? {
      return copied
    }
  }

  return Err(
    kbuild.ScriptError.Failed(
      "linux-config-fragment-missing",
      f"missing kernel config fragment ${input.display()} from staged source or typed recipe directory",
    ),
  )
}

## Resolves declared Linux config inputs from verified source staging or the copied typed recipe.
## It deliberately never interprets an input relative to the build process cwd.
export proc resolve_config_fragments(inputs: List[Path]) [fs, env, error] -> Result[List[Path]] {
  var fragments: List[Path] = []

  for input in inputs {
    fragments = fragments.push(resolved_fragment_input(input)?)
  }

  fragments
}

proc render_fragments(fragments: List[Path]) [fs, error] -> Result[Str] {
  var out = """# Generated by linux_config.xsh from package config fragments.
#
"""

  for fragment in fragments {
    if ! fragment.exists()? {
      return Err(
        kbuild.ScriptError.Failed("linux-config-fragment-missing", f"missing kernel config fragment ${fragment.display()}"),
      )
    }

    out = f"""${out}${fragment.read_text()?.trim()}
"""
  }

  return out
}

## Exported declaration `write_resolved_config`.
export proc write_resolved_config(root: Path, srcarch: Str, fragments: List[Path], out: Path) [fs, error] {
  let _ = {root: root.display(), srcarch}
  kbuild.write_text_if_changed(out, render_fragments(fragments)?)?
}
